export const TASK_REQUEST = "TASK_REQUEST";
export const TASK_REQUEST_FAIL = "TASK_REQUEST_FAIL";
export const TASK_REQUEST_SUCCESS = "TASK_REQUEST_SUCCESS";
export const ADD_TASK_REQUEST_SUCCESS = "ADD_TASK_REQUEST";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS";
